package com.cts.ms.model;

import org.apache.log4j.Logger;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "MERCHANTS_TABLE_NAME")
public class Merchants {

    private Logger logger = Logger.getLogger(this.getClass());

    private long mid;
    private String merchantName;
    private String organizationName;
    private String street;
    private String city;
    private String state;
    private String country;
    private String postalCode;
    private String emailAddress;
    private String url;
    private String phoneNumber;
    private String legalName;
    private String midTransactionLimit;
    private String purchaseCurrency;
    private String settlementCurrency;
    private String primaryFundingMethod;
    private String bankCity;
    private String bankCountry;
    private String billingProfileName;
    private String timeZone;
    private long floatDays;
    private String acquiringBank;
    private String activationDate;
    private String deActivationDate;
    private String createDate;

    @DynamoDBHashKey(attributeName = "mid")
//    @DynamoDBAutoGeneratedKey
    public long getMid() {
        return mid;
    }

    public void setMid(long mid) {
        this.mid = mid;
    }

    @DynamoDBAttribute(attributeName = "merchantName")
    public String getMerchantName() {
        return merchantName;
    }
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    @DynamoDBAttribute(attributeName = "organizationName")
    public String getOrganizationName() {
        return organizationName;
    }
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName;
    }

    @DynamoDBAttribute(attributeName = "street")
    public String getStreet() {
        return street;
    }
    public void setStreet(String street) {
        this.street = street;
    }

    @DynamoDBAttribute(attributeName = "city")
    public String getCity() {
        return city;
    }
    public void setCity(String city) {
        this.city = city;
    }

    @DynamoDBAttribute(attributeName = "state")
    public String getState() {
        return state;
    }
    public void setState(String state) {
        this.state = state;
    }

    @DynamoDBAttribute(attributeName = "country")
    public String getCountry() {
        return country;
    }
    public void setCountry(String country) {
        this.country = country;
    }

    @DynamoDBAttribute(attributeName = "postalCode")
    public String getPostalCode() {
        return postalCode;
    }
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    @DynamoDBAttribute(attributeName = "emailAddress")
    public String getEmailAddress() {
        return emailAddress;
    }
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    @DynamoDBAttribute(attributeName = "url")
    public String getUrl() {
        return url;
    }
    public void setUrl(String url) {
        this.url = url;
    }

    @DynamoDBAttribute(attributeName = "phoneNumber")
    public String getPhoneNumber() {
        return phoneNumber;
    }
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @DynamoDBAttribute(attributeName = "legalName")
    public String getLegalName() {
        return legalName;
    }
    public void setLegalName(String legalName) {
        this.legalName = legalName;
    }

    @DynamoDBAttribute(attributeName = "midTransactionLimit")
    public String getMidTransactionLimit() {
        return midTransactionLimit;
    }
    public void setMidTransactionLimit(String midTransactionLimit) {
        this.midTransactionLimit = midTransactionLimit;
    }

    @DynamoDBAttribute(attributeName = "purchaseCurrency")
    public String getPurchaseCurrency() {
        return purchaseCurrency;
    }
    public void setPurchaseCurrency(String purchaseCurrency) {
        this.purchaseCurrency = purchaseCurrency;
    }

    @DynamoDBAttribute(attributeName = "settlementCurrency")
    public String getSettlementCurrency() {
        return settlementCurrency;
    }
    public void setSettlementCurrency(String settlementCurrency) {
        this.settlementCurrency = settlementCurrency;
    }

    @DynamoDBAttribute(attributeName = "primaryFundingMethod")
    public String getPrimaryFundingMethod() {
        return primaryFundingMethod;
    }
    public void setPrimaryFundingMethod(String primaryFundingMethod) {
        this.primaryFundingMethod = primaryFundingMethod;
    }

    @DynamoDBAttribute(attributeName = "bankCity")
    public String getBankCity() {
        return bankCity;
    }
    public void setBankCity(String bankCity) {
        this.bankCity = bankCity;
    }

    @DynamoDBAttribute(attributeName = "bankCountry")
    public String getBankCountry() {
        return bankCountry;
    }
    public void setBankCountry(String bankCountry) {
        this.bankCountry = bankCountry;
    }

    @DynamoDBAttribute(attributeName = "billingProfileName")
    public String getBillingProfileName() {
        return billingProfileName;
    }
    public void setBillingProfileName(String billingProfileName) {
        this.billingProfileName = billingProfileName;
    }

    @DynamoDBAttribute(attributeName = "timeZone")
    public String getTimeZone() {
        return timeZone;
    }
    public void setTimeZone(String timeZone) {
        this.timeZone = timeZone;
    }

    @DynamoDBAttribute(attributeName = "floatDays")
    public long getFloatDays() {
        return floatDays;
    }
    public void setFloatDays(long floatDays) {
        this.floatDays = floatDays;
    }

    @DynamoDBAttribute(attributeName = "acquiringBank")
    public String getAcquiringBank() {
        return acquiringBank;
    }
    public void setAcquiringBank(String acquiringBank) {
        this.acquiringBank = acquiringBank;
    }

    @DynamoDBAttribute(attributeName = "activationDate")
    public String getActivationDate() {
        return activationDate;
    }

    public void setActivationDate(String activationDate) {
        this.activationDate = activationDate;
    }

    @DynamoDBAttribute(attributeName = "deActivationDate")
    public String getDeActivationDate() {
        return deActivationDate;
    }

    public void setDeActivationDate(String deActivationDate) {
        this.deActivationDate = deActivationDate;
    }

    @DynamoDBAttribute(attributeName = "createDate")
    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) (mid ^ (mid >>> 32));
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Merchants other = (Merchants) obj;
        if (mid != other.mid)
            return false;
        return true;
    }
    @Override
    public String toString() {
        return "Merchants [mid=" + mid + ", merchantName=" + merchantName + ", organizationName=" + organizationName
                + ", street=" + street + ", city=" + city + ", state=" + state + ", country=" + country
                + ", postalCode=" + postalCode + ", emailAddress=" + emailAddress + ", url=" + url + ", phoneNumber="
                + phoneNumber + ", legalName=" + legalName + ", midTransactionLimit=" + midTransactionLimit
                + ", purchaseCurrency=" + purchaseCurrency + ", settlementCurrency=" + settlementCurrency
                + ", primaryFundingMethod=" + primaryFundingMethod + ", bankCity=" + bankCity + ", bankCountry="
                + bankCountry + ", billingProfileName=" + billingProfileName + ", timeZone=" + timeZone + ", floatDays="
                + floatDays + ", acquiringBank=" + acquiringBank + ", activationDate=" + activationDate
                + ", deActivationDate=" + deActivationDate + ", createDate=" + createDate + "]";
    }

}
